apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivashko-api-gateway-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: merewhale/api-gateway:1.0.0
        env:
        - name: PYTHONPATH
          value: /workspace/src/app
        - name: POSTGRES_HOST
          value: http://postgres-service:5432
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: iivashko
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"

